// Generated by CoffeeScript 1.6.2
(function() {
  var App, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App = (function(_super) {
    __extends(App, _super);

    function App() {
      _ref = App.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    App.events({
      '.nav-tabs a': {
        click: 'initTabs'
      }
    });

    App.onDomReady(['initCarousel', 'initTabs']);

    App.prototype.initCarousel = function() {
      return $('.carousel').carousel();
    };

    App.prototype.initTabs = function(e) {
      $(e.currentTarget).tab('show');
      return false;
    };

    return App;

  })(Framework);

}).call(this);
