// Generated by CoffeeScript 1.7.1
(function() {
  var Locale;

  Locale = (function() {
    function Locale() {}

    Locale.prototype.isInitialized = false;

    Locale.prototype.data = null;

    Locale.prototype.initialize = function() {
      return $.ajax('/cache/locale/' + Data.get('core.language') + '.json', {
        type: 'GET',
        dataType: 'json',
        async: false,
        success: (function(_this) {
          return function(data) {
            _this.data = data;
            return _this.isInitialized = true;
          };
        })(this),
        error: function(jqXHR, textStatus, errorThrown) {
          throw Error('Regenerate your locale-files.');
        }
      });
    };

    false;

    Locale.prototype.exists = function(key) {
      return this.get(key) != null;
    };

    Locale.prototype.get = function(type, key) {
      if (!this.isInitialized) {
        this.initialize();
      }
      if (this.data[type][key] == null) {
        return '{$' + type + key + '}';
      }
      return this.data[type][key];
    };

    Locale.prototype.act = function(key) {
      return this.get('act', key);
    };

    Locale.prototype.err = function(key) {
      return this.get('err', key);
    };

    Locale.prototype.lbl = function(key) {
      return this.get('lbl', key);
    };

    Locale.prototype.loc = function(key) {
      return this.get('loc', key);
    };

    Locale.prototype.msg = function(key) {
      return this.get('msg', key);
    };

    return Locale;

  })();

  window.Locale = new Locale;

}).call(this);
