source 'http://rubygems.org'

gem 'compass'
gem 'compass_twitter_bootstrap', '2.3.1'
gem 'compass_sumo'
gem 'foreman'
gem 'capistrano', '~> 2.15'
gem 'sumodev_deploy', '~> 0.7.0'
gem 'forkcms_deploy', '>= 2.7.0'
gem 'sumodev', '~> 0.10.0'
