<?php

/**
 * This is our extended version of SpoonForm
 *
 * @package		site
 * @subpackage	core
 *
 * @author		Tijs Verkoyen <tijs@sumocoders.be>
 * @since		2.0
 */
class SiteForm extends SpoonForm
{
	/**
	 * Class constructor.
	 *
	 * @param	string $name				Name of the form.
	 * @param	string[optional] $action	The action (URL) whereto the form will be submitted, if not provided it will be autogenerated.
	 * @param	string[optional] $method	The method to use when submiting the form, default is POST.
	 * @param	bool[optional] $useToken	Should we automagically add a formtoken?
	 * @return void
	 */
	public function __construct($name, $action = null, $method = 'post', $useToken = false)
	{
		// no acion provided?
		$action = ($action === null) ? '/' . trim((string) $_SERVER['REQUEST_URI'], '/') : (string) $action;

		// call parent
		parent::__construct($name, $action, $method, $useToken);
	}
}
